apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
  namespace: {{ .Values.namespace }}
spec:
  version: {{ .Values.elasticsearch.version }}
  nodeSets:
    - name: default
      count: {{ .Values.replicaCount }}
      config:
        node.roles:
          - master
          - data
          - ingest
        node.attr.attr_name: attr_value
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
              {{- if .Values.esJavaOpts  }}
              - name: ES_JAVA_OPTS
                value: "{{ .Values.esJavaOpts }}"
              {{- end }}
              - name: READINESS_PROBE_TIMEOUT
                value: "10"
              resources:
                {{- toYaml .Values.resources | nindent 10 }}
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        elasticsearch.k8s.elastic.co/cluster-name: {{ include "es.fullname" . }}
                    topologyKey: kubernetes.io/hostname

