# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: els

replicaCount: 1

elasticsearch:
  version: 7.15.1

esJavaOpts: "-Xmx128m -Xms128m"

podAnnotations: {}

resources:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "1000m"
    memory: "2Gi"
